# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('tri', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Comment',
                'ordering': ('tri',),
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='ImgBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='evil.gif', upload_to='')),
                ('tri', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Building Gallery',
                'ordering': ('tri',),
                'verbose_name_plural': 'Building Galleries',
            },
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.RemoveField(
            model_name='building',
            name='address',
        ),
        migrations.AddField(
            model_name='building',
            name='area',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='building',
            name='buildingtype',
            field=models.CharField(default='NA', max_length=200, verbose_name='Building class'),
        ),
        migrations.AddField(
            model_name='building',
            name='com_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='construction_type',
            field=models.CharField(default='NA', max_length=200, verbose_name='Construction type'),
        ),
        migrations.AddField(
            model_name='building',
            name='five',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='four',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='grade',
            field=models.CharField(default='NA', max_length=200, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.CharField(default=0, max_length=10, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.CharField(default=0, max_length=10, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='building',
            name='lotsize',
            field=models.IntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='building',
            name='marketvalue',
            field=models.IntegerField(default=10000000),
        ),
        migrations.AddField(
            model_name='building',
            name='one',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='res_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='stories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='streetname',
            field=models.CharField(default='NA', max_length=200, verbose_name='Street name'),
        ),
        migrations.AddField(
            model_name='building',
            name='streetnumber',
            field=models.CharField(default='NA', max_length=5, verbose_name='Street number'),
        ),
        migrations.AddField(
            model_name='building',
            name='structure_type',
            field=models.CharField(default='NA', max_length=200, verbose_name='Structure type'),
        ),
        migrations.AddField(
            model_name='building',
            name='three',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='two',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='yearbuilt',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='building',
            name='zipcode',
            field=models.CharField(default=0, max_length=5, verbose_name='Zipcode'),
        ),
        migrations.AddField(
            model_name='imgbuilding',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uboapp.Building'),
        ),
        migrations.AddField(
            model_name='comment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uboapp.Building'),
        ),
    ]
