# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='address',
        ),
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='building',
            name='streetname',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='building',
            name='streetnum',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='building',
            name='zipcode',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
