# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0007_auto_20161028_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(default='uboapp/media/evil.gif', upload_to='uboapp/media/'),
        ),
    ]
