# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0008_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='buildingtype',
            new_name='building_class',
        ),
    ]
