# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0009_auto_20161028_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.CharField(default=0, max_length=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.CharField(default=0, max_length=10, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='building',
            name='streetname',
            field=models.CharField(default=0, max_length=200, verbose_name='Street name'),
        ),
        migrations.AlterField(
            model_name='building',
            name='streetnum',
            field=models.CharField(default=0, max_length=5, verbose_name='Street number'),
        ),
        migrations.AlterField(
            model_name='building',
            name='zipcode',
            field=models.CharField(default=0, max_length=5, verbose_name='Zipcode'),
        ),
    ]
