# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0009_auto_20161204_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='grade',
            new_name='rate',
        ),
    ]
