# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0011_auto_20161028_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgbuilding',
            name='tri',
            field=models.IntegerField(default=0),
        ),
    ]
