# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0012_imgbuilding_tri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.AlterModelOptions(
            name='imgbuilding',
            options={'ordering': ('tri',), 'verbose_name': 'Building Gallery', 'verbose_name_plural': 'Building Galleries'},
        ),
        migrations.RenameField(
            model_name='building',
            old_name='streetnum',
            new_name='streetnumber',
        ),
    ]
