# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import uboapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0016_auto_20161028_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgbuilding',
            name='image',
            field=models.ImageField(default='media/evil.gif', upload_to=uboapp.models.building_upload_to),
        ),
    ]
