# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0017_auto_20161028_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgbuilding',
            name='image',
            field=models.ImageField(default='uboapp/media/evil.gif', upload_to='uboapp/media/'),
        ),
    ]
