# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0018_auto_20161028_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgbuilding',
            name='image',
            field=models.ImageField(default='evil.gif', upload_to='uboapp/media/'),
        ),
    ]
