# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0019_auto_20161029_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgbuilding',
            name='image',
            field=models.ImageField(default='evil.gif', upload_to=''),
        ),
    ]
