# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0020_auto_20161029_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='yearbuilt',
            field=models.IntegerField(default=2000),
        ),
    ]
