# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0023_auto_20161101_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='height',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='building',
            name='stories',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='building',
            name='units',
            field=models.IntegerField(default=50),
        ),
    ]
