# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0024_auto_20161104_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='five',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='four',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='one',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='three',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='building',
            name='two',
            field=models.IntegerField(default=0),
        ),
    ]
