# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0025_auto_20161109_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='buildingarea',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='building',
            name='buildingcode',
            field=models.CharField(default='D1', max_length=2, verbose_name='Building Code'),
        ),
        migrations.AddField(
            model_name='building',
            name='lotsize',
            field=models.IntegerField(default=50000),
        ),
    ]
