# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0026_auto_20161112_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='buildingcode',
        ),
        migrations.RemoveField(
            model_name='building',
            name='lotsize',
        ),
        migrations.AddField(
            model_name='building',
            name='buildingtype',
            field=models.CharField(default='TBD', max_length=50, verbose_name='Building Type'),
        ),
    ]
