# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0027_auto_20161113_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='height',
        ),
        migrations.AddField(
            model_name='building',
            name='lotsize',
            field=models.IntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='building',
            name='marketvalue',
            field=models.IntegerField(default=10000000),
        ),
        migrations.AlterField(
            model_name='building',
            name='buildingtype',
            field=models.CharField(default=0, max_length=200, verbose_name='Building type'),
        ),
    ]
