# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0028_auto_20161117_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='buildingarea',
            new_name='area',
        ),
    ]
