# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uboapp', '0029_auto_20161117_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='units',
            new_name='res_units',
        ),
        migrations.AddField(
            model_name='building',
            name='com_units',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='building',
            name='construction_type',
            field=models.CharField(default='NA', max_length=200, verbose_name='Construction type'),
        ),
        migrations.AddField(
            model_name='building',
            name='grade',
            field=models.CharField(default='NA', max_length=200, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='building',
            name='structure_type',
            field=models.CharField(default='NA', max_length=200, verbose_name='Structure type'),
        ),
        migrations.AlterField(
            model_name='building',
            name='buildingtype',
            field=models.CharField(default='NA', max_length=200, verbose_name='Building class'),
        ),
        migrations.AlterField(
            model_name='building',
            name='streetname',
            field=models.CharField(default='NA', max_length=200, verbose_name='Street name'),
        ),
        migrations.AlterField(
            model_name='building',
            name='streetnumber',
            field=models.CharField(default='NA', max_length=5, verbose_name='Street number'),
        ),
    ]
